kind: pipeline
type: docker
name: deploy

clone:
  disable: true

steps:
  - name: deploy
    image: appleboy/drone-ssh:1.6.3
    settings:
      host: 101.42.135.206
      username: ubuntu
      password:
        from_secret: server_password
      port: 22
      script:
        - cd /home/ubuntu/code/megrez 
        - git pull 
        - export PATH=$PATH:/home/ubuntu/.nvm/versions/node/v16.13.0/bin
        - node index.js 
        # - workbox generateSW workbox-config.js 
        # - /home/ubuntu/.nvm/versions/node/v16.13.0/bin/pnpm run build
        - sudo nginx -s reload

  - name: email
    image: drillster/drone-email
    settings:
      subject: '个人知识库Megrez部署: [{{ build.status }}] ({{ repo.branch }}) #{{ build.number }}'
      host: smtp.qq.com
      port: 465
      from: 
        from_secret: email_user
      username:
        from_secret: email_user
      password:
        from_secret: email_password
      recipients: 2633419446@qq.com
      recipients_only: true
    when:
      status:
        - success
        - changed
        - failure

  - name: 章鱼星球
    image: appleboy/drone-ssh:1.6.3
    settings:
      host: iric.tpddns.cn
      username: root
      password:
        from_secret: armbian_password
      port: 22
      script:
        - cd /root/code/megrez 
        - git pull 
        - export PATH=$PATH:/root/.nvm/versions/node/v16.13.0/bin
        - node index.js 
        - sudo nginx -s reload

trigger:
  event:
    - push
  branch:
    - master