kind: pipeline
type: docker
name: deploy

clone:
  disable: true

steps:
  - name: deploy
    image: appleboy/drone-ssh:1.6.3
    settings:
      host: 101.42.135.206
      username: ubuntu
      password:
        from_secret: server_password
      port: 22
      script:
        - cd /home/ubuntu/code/megrez && git pull && /home/ubuntu/.nvm/versions/node/v16.13.0/bin/node index.js && sudo nginx -s reload

  - name: email
    image: drillster/drone-email
    settings:
      subject: '个人知识库Megrez部署: [{{ build.status }}] ({{ repo.branch }}) #{{ build.number }}'
      host: smtp.qq.com
      port: 465
      from: 
        from_secret: email_user
      username:
        from_secret: email_user
      password:
        from_secret: email_password
      recipients: 2633419446@qq.com
      recipients_only: true
    when:
      status:
        - success
        - changed
        - failure

trigger:
  event:
    - push
  branch:
    - master

---
kind: pipeline
type: docker
name: build

clone:
  disable: true

steps:
  - name: clone
    image: alpine/git:v2.32.0
    environment:
      SSH_KEY:
        from_secret: deploy_key
    commands:
      - mkdir -p /root/.ssh/
      - echo "$SSH_KEY" > /root/.ssh/id_rsa
      - chmod -R 600 /root/.ssh/
      - ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts
      - git clone -v git@github.com:IricBing/megrez.git .

  - name: build
    image: plugins/docker:20.10.9
    settings:
      repo: iricbing/megrez
      username: iricbing
      password: zh.2015.
      tags: latest
      no_cache: true

  - name: email
    image: drillster/drone-email
    settings:
      subject: '个人知识库Megrez构建: [{{ build.status }}] ({{ repo.branch }}) #{{ build.number }}'
      host: smtp.qq.com
      port: 465
      from: 
        from_secret: email_user
      username:
        from_secret: email_user
      password:
        from_secret: email_password
      recipients: 2633419446@qq.com
      recipients_only: true
    when:
      status:
        - success
        - changed
        - failure

trigger:
  event:
    - push
  branch:
    - master